---
- name: Run oracle_sql task
  hosts: oracle1.localdomain
  gather_facts: yes
  tasks:
    - name: Execute SQL Query
      oracle_sql:
        username: "system"
        password: "Opera123"
        service_name: "orclcdb"
        port: "1521"
        hostname : "oracle1.localdomain"
        sql: "SELECT * FROM dba_users"
      register: query_result

    - debug:
        var: query_result

